from .pairwiseScoringParadigm import PairwiseScoringParadigm
from .interGroupScoringParadigm import InterGroupScoringParadigm
from .holisticScoringParadigm import HolisticScoringParadigm
from .scoringParadigm import ScoringParadigm
